name: roomadda
description: "Finding room near me."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  dart_format: ^1.1.17
  curved_navigation_bar: ^1.0.3
  dropdown_button2: ^2.3.9
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.0
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  get: ^4.6.6

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        
    
                                      